name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - uses: retypeapp/action-build@latest
        with:
          config_path: ./docs/retype.yml

      - uses: 1arp/create-a-file-action@0.4.5
        with:
          path: '.'
          isAbsolutePath: false
          file: 'script.sh'
          content: |
            #!/bin/bash

            # https://vercel.com/guides/how-do-i-use-the-ignored-build-step-field-on-vercel

            echo "VERCEL_GIT_COMMIT_REF: $VERCEL_GIT_COMMIT_REF"

            if [[ "$VERCEL_GIT_COMMIT_REF" == "main" || "$VERCEL_GIT_COMMIT_REF" == "cms" || "$VERCEL_GIT_COMMIT_REF" == "feat/cms"  ]] ; then
              # Proceed with the build
                echo "✅ - Build can proceed"
              exit 1;

            else
              # Don't build
              echo "🛑 - Build cancelled"
              exit 0;
            fi

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
